# Generated by Django 6.0 on 2025-12-09 14:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_session_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationmutuelle',
            name='coefficient_emprunt_max',
        ),
        migrations.CreateModel(
            name='EmpruntCoefficientTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant minimum (FCFA)')),
                ('max_amount', models.PositiveBigIntegerField(verbose_name='Montant maximum (FCFA)')),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Coefficient')),
                ('max_cap', models.PositiveBigIntegerField(blank=True, help_text='Ex: 2 000 000 FCFA – seulement pour la première tranche', null=True, verbose_name='Plafond absolu (optionnel)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunt_tiers', to='core.exercice', verbose_name='Exercice')),
            ],
            options={
                'verbose_name': 'Tranche coefficient emprunt',
                'verbose_name_plural': 'Tranches coefficients emprunt',
                'ordering': ['min_amount'],
                'unique_together': {('exercise', 'min_amount')},
            },
        ),
    ]
