# Generated by Django 6.0 on 2026-01-04 23:39

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_configurationmutuelle_coefficient_emprunt_max_and_more'),
        ('transactions', '0003_emprunt_date_creation_emprunt_date_modification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant perçu (FCFA)')),
                ('date_distribution', models.DateTimeField(auto_now_add=True)),
                ('emprunt_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redistributions', to='transactions.emprunt', verbose_name='Emprunt source')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exercice', verbose_name='Exercice')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gains_interets', to='core.membre', verbose_name='Membre bénéficiaire')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.session', verbose_name='Session de distribution')),
            ],
            options={
                'verbose_name': 'Intérêt redistribué',
                'verbose_name_plural': 'Intérêts redistribués',
                'ordering': ['-date_distribution'],
            },
        ),
    ]
