# Generated by Django 6.0.1 on 2026-01-21 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_interet'),
        ('core', '0007_populate_montants_dus'),
    ]

    operations = [
    ]
