# Generated by Django 5.2.8 on 2026-01-26 17:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_0006_interet_0007_populate_montants_dus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='statut',
            field=models.CharField(choices=[('EN_REGLE', 'En règle'), ('NON_EN_REGLE', 'Non en règle'), ('SUSPENDU', 'Suspendu'), ('NON_DEFINI', 'Non defini')], default='NON_DEFINI', max_length=15, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='DépenseExercice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_depense', models.CharField(choices=[('ASSISTANCE', 'Assistance'), ('COLLATION', 'Collation'), ('AUTRE', 'Autre')], max_length=15, verbose_name='Type de dépense')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant (FCFA)')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('beneficiaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aides_reçues', to='core.membre', verbose_name='Bénéficiaire (si applicable)')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='core.exercice', verbose_name='Exercice')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='core.session')),
            ],
            options={
                'verbose_name': "Dépense d'exercice",
                'verbose_name_plural': "Dépenses d'exercice",
                'ordering': ['-date_creation'],
            },
        ),
    ]
