# Generated by Django 6.0.3 on 2026-03-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_membre_statut_dépenseexercice'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='actif',
            field=models.BooleanField(default=True, help_text='False si le membre ne fait plus partie de la mutuelle', verbose_name='Membre actif'),
        ),
    ]
