# Generated by Django 6.0.3 on 2026-03-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_membre_statut_dépenseexercice'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE core_membre ADD COLUMN IF NOT EXISTS actif boolean DEFAULT true;",
            reverse_sql="ALTER TABLE core_membre DROP COLUMN IF EXISTS actif;"
        ),
    ]
