# Generated by Django 5.2.12 on 2026-03-07 05:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_membre_statut_dépenseexercice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaisseInscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant total de la caisse inscription (FCFA)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('exercice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caisse_inscription', to='core.exercice')),
            ],
            options={
                'verbose_name': 'Caisse inscription',
                'verbose_name_plural': 'Caisses inscription',
            },
        ),
        migrations.CreateModel(
            name='MouvementCaisseInscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('caisse_inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='core.caisseinscription')),
            ],
            options={
                'verbose_name': 'Mouvement caisse inscription',
                'verbose_name_plural': 'Mouvements caisse inscription',
                'ordering': ['-date_mouvement'],
            },
        ),
    ]
