# Generated by Django 5.2.12 on 2026-03-09 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_caisse_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='montant_autre_depense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Autre dépense (FCFA)'),
        ),
        migrations.AddField(
            model_name='session',
            name='motif_autre_depense',
            field=models.TextField(blank=True, verbose_name='Motif autre dépense'),
        ),
    ]
