# Generated by Django 5.2.12 on 2026-03-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_session_autre_depense'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
    ]
