# Generated by Django 6.0.3 on 2026-03-16 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_membre_actif'),
        ('core', '0012_membre_actif'),
    ]

    operations = [
    ]
