# Generated by Django 5.2.12 on 2026-03-21 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_0010_membre_actif_0012_membre_actif'),
        ('transactions', '0008_unique_paiement_inscription_par_membre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interet',
            name='emprunt_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redistributions', to='transactions.emprunt', verbose_name='Emprunt source'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
    ]
