# Generated by Django 5.2.12 on 2026-05-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_solidarite_exercice_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolidariteExerciceReport',
        ),
    ]
