# Generated by Django 5.2.12 on 2026-05-25 10:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_delete_solidariteexercicereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolidariteExerciceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant_reporte', models.DecimalField(decimal_places=2, help_text='Positif = dette à payer sur le prochain exercice. Négatif = surplus (crédit).', max_digits=12, verbose_name='Montant reporté (FCFA)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('exercice_cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_solidarite_recus', to='core.exercice', verbose_name='Exercice cible (nouveau)')),
                ('exercice_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_solidarite_emis', to='core.exercice', verbose_name='Exercice source (clôturé)')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_solidarite', to='core.membre', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Report de solidarité',
                'verbose_name_plural': 'Reports de solidarité',
                'ordering': ['-date_creation'],
                'unique_together': {('membre', 'exercice_source')},
            },
        ),
    ]
