# Generated by Django 5.2.12 on 2026-05-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_solidariteexercicereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='solidarite_terminee',
            field=models.BooleanField(default=False, help_text='True si le membre a payé la totalité de sa solidarité (une fois dans sa vie)', verbose_name='Solidarité terminée'),
        ),
    ]
