# Generated by Django 6.0.3 on 2026-07-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_membre_solidarite_terminee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='statut',
            field=models.CharField(choices=[('EN_REGLE', 'En règle'), ('NON_EN_REGLE', 'Non en règle')], default='EN_REGLE', max_length=15, verbose_name='Statut'),
        ),
    ]
