# Generated by Django 5.2.8 on 2026-01-26 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_add_montant_dus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementinscription',
            name='montant_inscription_du',
            field=models.DecimalField(decimal_places=2, help_text="Montant configuré au moment de l'inscription du membre", max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Montant total dû pour l'inscription (FCFA)"),
        ),
        migrations.AlterField(
            model_name='paiementsolidarite',
            name='montant_solidarite_du',
            field=models.DecimalField(decimal_places=2, help_text='Montant configuré au moment du paiement de cette session', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant dû pour cette session (FCFA)'),
        ),
        migrations.AlterField(
            model_name='renflouement',
            name='type_cause',
            field=models.CharField(choices=[('ASSISTANCE', 'Assistance'), ('COLLATION', 'Collation'), ('RENFLOUEMENT_FIN_EXERCICE', "Renflouement fin d'exercice"), ('AUTRE', 'Autre')], max_length=40, verbose_name='Type de cause'),
        ),
    ]
