# Generated by Django 6.0.3 on 2026-03-28 06:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_unique_paiement_inscription_par_membre'),
    ]

    operations = [
        migrations.AddField(
            model_name='renflouement',
            name='ratio_caisse_inscription',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.5'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Ratio vers CaisseInscription (0-1)'),
        ),
        migrations.AddField(
            model_name='renflouement',
            name='ratio_fonds_social',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.5'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Ratio vers FondsSocial (0-1)'),
        ),
        migrations.AlterField(
            model_name='paiementsolidarite',
            name='montant_solidarite_du',
            field=models.DecimalField(decimal_places=2, help_text='Montant configuré au moment du paiement de cet exercice', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant dû pour cette exercice (FCFA)'),
        ),
    ]
