# Generated by Django 5.2.12 on 2026-04-25 06:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_unique_paiement_inscription_par_membre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementsolidarite',
            name='montant_solidarite_du',
            field=models.DecimalField(decimal_places=2, help_text='Montant configuré au moment du paiement de cet exercice', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant dû pour cette exercice (FCFA)'),
        ),
    ]
