# Generated by Django 6.0.3 on 2026-03-28 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_solidarite_exercice_report'),
        ('transactions', '0009_renflouement_ratio_caisse_inscription_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paiementinscription',
            name='unique_paiement_inscription_par_membre',
        ),
        migrations.RemoveField(
            model_name='renflouement',
            name='session',
        ),
        migrations.AddField(
            model_name='renflouement',
            name='exercice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renflouements', to='core.exercice', verbose_name='Exercice'),
        ),
    ]
