# Generated by Django 6.0.3 on 2026-05-28 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_retraitepargne'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paiementinscription',
            name='unique_paiement_inscription_par_membre',
        ),
        migrations.AlterField(
            model_name='retraitepargne',
            name='epargne_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrait_source', to='transactions.epargnetransaction', verbose_name="Transaction d'épargne liée"),
        ),
    ]
