# Generated by Django 5.2.12 on 2026-04-25 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_paiementsolidarite_montant_solidarite_du'),
        ('transactions', '0010_remove_paiementinscription_unique_paiement_inscription_par_membre_and_more'),
    ]

    operations = [
    ]
