# Generated by Django 5.2.12 on 2026-04-25 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_solidarite_exercice_report'),
        ('transactions', '0011_merge_20260425_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renflouement',
            name='exercice',
        ),
        migrations.RemoveField(
            model_name='renflouement',
            name='ratio_caisse_inscription',
        ),
        migrations.RemoveField(
            model_name='renflouement',
            name='ratio_fonds_social',
        ),
        migrations.AddField(
            model_name='renflouement',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renflouements', to='core.session'),
        ),
        migrations.AddConstraint(
            model_name='paiementinscription',
            constraint=models.UniqueConstraint(fields=('membre',), name='unique_paiement_inscription_par_membre'),
        ),
    ]
