# Generated by Django 6.0.3 on 2026-05-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_remove_renflouement_exercice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='epargnes_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text="Enregistre les épargnes de chaque membre au moment de l'emprunt pour les redistributions futures", null=True, verbose_name='Épargnes snapshot à la création'),
        ),
    ]
