# Generated by Django 6.0.3 on 2026-05-19 07:15

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_solidarite_exercice_report'),
        ('transactions', '0013_emprunt_epargnes_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaliteEmprunt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_penalite', models.CharField(choices=[('RETARD_PALIER', 'Pénalité de retard par palier'), ('RETARD_MANUEL', 'Pénalité manuelle')], default='RETARD_PALIER', max_length=20, verbose_name='Type de pénalité')),
                ('palier', models.CharField(help_text='Indique à quel palier cette pénalité a été appliquée', max_length=20, verbose_name='Palier (ex: Palier-3, Palier-6)')),
                ('sessions_ecoulees', models.IntegerField(help_text="Nombre de sessions depuis l'octroi de l'emprunt", verbose_name='Nombre de sessions écoulées')),
                ('montant_reste_avant', models.DecimalField(decimal_places=2, help_text='Le montant qui restait à rembourser avant cette pénalité', max_digits=12, verbose_name='Montant restant avant pénalité (FCFA)')),
                ('taux_applique', models.DecimalField(decimal_places=2, help_text='Le taux utilisé pour calculer la pénalité', max_digits=5, verbose_name="Taux d'intérêt appliqué (%)")),
                ('montant_interet_taux', models.DecimalField(decimal_places=2, help_text='Montant calculé: reste_à_payer × taux_intérêt', max_digits=12, verbose_name='Montant intérêt (reste × taux) (FCFA)')),
                ('montant_penalite_fixe', models.DecimalField(decimal_places=2, default=Decimal('15000'), help_text='Montant fixe de pénalité (généralement 15 000 FCFA)', max_digits=12, verbose_name='Pénalité fixe (FCFA)')),
                ('montant_total_penalite', models.DecimalField(decimal_places=2, help_text='Somme: intérêt_taux + pénalité_fixe', max_digits=12, verbose_name='Total pénalité (FCFA)')),
                ('date_application', models.DateTimeField(auto_now_add=True, verbose_name="Date d'application")),
                ('justification', models.TextField(blank=True, help_text='Explication détaillée de pourquoi cette pénalité a été appliquée', verbose_name='Justification')),
                ('notes_complementaires', models.TextField(blank=True, verbose_name='Notes complémentaires')),
                ('appliquee_par', models.ForeignKey(blank=True, help_text='Utilisateur qui a déclenché cette pénalité (ou système automatique)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Appliquée par')),
                ('emprunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalites', to='transactions.emprunt')),
                ('session_application', models.ForeignKey(help_text='Session pendant laquelle cette pénalité a été appliquée', on_delete=django.db.models.deletion.CASCADE, to='core.session', verbose_name="Session d'application")),
            ],
            options={
                'verbose_name': "Pénalité d'emprunt",
                'verbose_name_plural': "Pénalités d'emprunts",
                'ordering': ['-date_application'],
                'indexes': [models.Index(fields=['emprunt', 'palier'], name='transaction_emprunt_fb46a1_idx'), models.Index(fields=['date_application'], name='transaction_date_ap_b35900_idx'), models.Index(fields=['type_penalite'], name='transaction_type_pe_1e5b7c_idx')],
                'unique_together': {('emprunt', 'palier')},
            },
        ),
    ]
