# Generated by Django 6.0.3 on 2026-05-19 07:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_solidarite_exercice_report'),
        ('transactions', '0014_penaliteemprunt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementrenflouement',
            name='montant_caisse_inscription',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Partie du paiement qui va à la caisse inscription', max_digits=12, verbose_name='Montant vers caisse inscription (FCFA)'),
        ),
        migrations.AddField(
            model_name='paiementrenflouement',
            name='montant_fonds_social',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Partie du paiement qui va au fonds social', max_digits=12, verbose_name='Montant vers fonds social (FCFA)'),
        ),
        migrations.AddField(
            model_name='paiementrenflouement',
            name='ratio_caisse_utilise',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ratio caisse inscription utilisé pour ce paiement', max_digits=5, null=True, verbose_name='Ratio caisse utilisé (%)'),
        ),
        migrations.AddField(
            model_name='paiementrenflouement',
            name='ratio_fonds_utilise',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ratio fonds social utilisé pour ce paiement', max_digits=5, null=True, verbose_name='Ratio fonds utilisé (%)'),
        ),
        migrations.AddField(
            model_name='renflouement',
            name='exercice_renflouement',
            field=models.ForeignKey(blank=True, help_text='Exercice pour lequel ce renflouement a été calculé', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renflouements_fin_exercice', to='core.exercice', verbose_name='Exercice de renflouement'),
        ),
        migrations.AddField(
            model_name='renflouement',
            name='ratio_caisse_inscription',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pourcentage des paiements qui va à la caisse inscription', max_digits=5, null=True, verbose_name='Ratio caisse inscription (%)'),
        ),
        migrations.AddField(
            model_name='renflouement',
            name='ratio_fonds_social',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pourcentage des paiements qui va au fonds social', max_digits=5, null=True, verbose_name='Ratio fonds social (%)'),
        ),
        migrations.CreateModel(
            name='RepartitionRenflouementExercice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_sorties_caisse_inscription', models.DecimalField(decimal_places=2, help_text='Somme de toutes les sorties de la caisse inscription', max_digits=15, verbose_name='Total sorties caisse inscription (FCFA)')),
                ('total_sorties_fonds_social', models.DecimalField(decimal_places=2, help_text='Somme de toutes les sorties du fonds social', max_digits=15, verbose_name='Total sorties fonds social (FCFA)')),
                ('total_sorties_global', models.DecimalField(decimal_places=2, help_text='Somme totale des sorties des deux caisses', max_digits=15, verbose_name='Total sorties global (FCFA)')),
                ('ratio_caisse_inscription', models.DecimalField(decimal_places=2, help_text='Pourcentage des sorties de la caisse inscription', max_digits=5, verbose_name='Ratio caisse inscription (%)')),
                ('ratio_fonds_social', models.DecimalField(decimal_places=2, help_text='Pourcentage des sorties du fonds social', max_digits=5, verbose_name='Ratio fonds social (%)')),
                ('nombre_membres_en_regle', models.IntegerField(help_text='Nombre de membres en règle au moment du calcul', verbose_name='Nombre de membres en règle')),
                ('nombre_membres_non_en_regle', models.IntegerField(help_text='Nombre de membres non en règle qui devront payer', verbose_name='Nombre de membres non en règle')),
                ('nombre_membres_total', models.IntegerField(help_text='Nombre total de membres actifs', verbose_name='Nombre total de membres')),
                ('montant_par_membre', models.DecimalField(decimal_places=2, help_text='Montant que chaque membre non en règle doit payer', max_digits=12, verbose_name='Montant par membre (FCFA)')),
                ('date_calcul', models.DateTimeField(auto_now_add=True, verbose_name='Date de calcul')),
                ('notes_calcul', models.TextField(blank=True, help_text='Détails supplémentaires sur le calcul', verbose_name='Notes de calcul')),
                ('calcule_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Calculé par')),
                ('exercice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repartition_renflouement', to='core.exercice', verbose_name='Exercice')),
            ],
            options={
                'verbose_name': 'Répartition renflouement exercice',
                'verbose_name_plural': 'Répartitions renflouements exercices',
                'ordering': ['-date_calcul'],
            },
        ),
    ]
