# Generated by Django 6.0.3 on 2026-05-19 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_paiementrenflouement_montant_caisse_inscription_and_more'),
    ]

    operations = [
    ]
