# Generated by Django 6.0.3 on 2026-05-29 20:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_alter_epargnetransaction_type_transaction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retraitepargne',
            options={'ordering': ['-date_retrait'], 'verbose_name': "Retrait d'épargne", 'verbose_name_plural': "Retraits d'épargne"},
        ),
        migrations.RemoveField(
            model_name='retraitepargne',
            name='date_demande',
        ),
        migrations.RemoveField(
            model_name='retraitepargne',
            name='date_traitement',
        ),
        migrations.RemoveField(
            model_name='retraitepargne',
            name='notes_admin',
        ),
        migrations.RemoveField(
            model_name='retraitepargne',
            name='statut',
        ),
        migrations.AddField(
            model_name='retraitepargne',
            name='date_retrait',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date du retrait'),
            preserve_default=False,
        ),
    ]
