# Generated by Django 6.0.3 on 2026-07-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_alter_retraitepargne_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epargnetransaction',
            name='type_transaction',
            field=models.CharField(choices=[('DEPOT', 'Dépôt'), ('RETRAIT_PRET', 'Retrait pour prêt'), ('AJOUT_INTERET', "Ajout d'intérêt"), ('RETOUR_REMBOURSEMENT', 'Retour de remboursement'), ('RETRAIT_EPARGNE', 'Retrait épargne'), ('RETRAIT_RENFLOUEMENT', 'Retrait pour renflouement')], max_length=20, verbose_name='Type de transaction'),
        ),
    ]
